# Site settings
title: My Github Notes
email: alberthardy@gmail.com
description: Online Notes running on Jekyll and Github Pages
baseurl: "/notes" # the subpath of your site, e.g. /blog/
url: "http://albhardy.github.io" # the base hostname & protocol for your site
twitter_username: alberthardy
github_username:  albhardy

# Build settings
markdown: kramdown
pygments:         false
highlighter:      null